# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy the .env file for the backend
COPY .env .env

# Expose the port your application is listening on
EXPOSE 4000

# Command to start your application
CMD [ "node", "main.js" ]
